import { type AppType } from "next/app";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import { api } from "~/utils/api";
import "react-toastify/dist/ReactToastify.css";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer autoClose={2500} />
      <Component {...pageProps} />;
    </>
  );
};

export default api.withTRPC(MyApp);
