import { type AppType } from "next/app";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import { api } from "~/utils/api";
import "react-toastify/dist/ReactToastify.css";
import store from "../app/store";
import { Provider } from "react-redux";
import "~/styles/globals.css";
import AppWrapper from "~/components/AppWrapper";
import useAuth from "~/hooks/useAuth";
import 'react-quill/dist/quill.snow.css';
const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer autoClose={2500} />
      <Provider store={store}>
        <AppWrapper>
          <Component {...pageProps} />
        </AppWrapper>
      </Provider>
    </>
  );
};

export default api.withTRPC(MyApp);
